name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install 
    - name: Set .env
      run: |
        echo "SECRET=${{ secrets.SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> .env
    - run: npm test
